In [53]:
import numpy as np
import pandas as pd
np.set_printoptions(formatter={'all':lambda x: 'int: '+str(-x)})
np.set_printoptions(suppress=True) #sopprime la notazione scientifica

In [54]:
df = pd.read_csv('dati2.txt',delimiter=' ')
df

col1  col2    col3  col4  col5     col6
0  1.000000  2.00   0.500    -5   0.0 -11.1666
1 -1.300000  1.00 -15.000     0   2.0  28.0000
2  0.333333  0.00   1.234    -4   4.0  56.5673
3  0.666600 -5.00   1.000    30  -1.0 -10.6661
4  0.000000  0.05   8.000   -12  -0.5  -3.5000

In [55]:
dim = np.shape(df)
n = dim[0]

In [56]:
A = df.iloc[:,:n].values #matrice A dei coefficienti del sistema
b = df.iloc[:,n:].values #vettore b dei termini noti
dim = np.shape(A)

In [57]:
#inizializzazione U ed L
U = np.zeros(dim)
L = np.zeros(dim)

for i in range(n):
    U[0][i] = A[0][i]
for j in range(1,n):
    L[j][0] = A[j][0]/U[0][0]

#definizione della prima riga di U
for i in range(n):
    U[i][i] = A[i][i] # così riempie solo la diagonale con elementi di A
    for j in range(i):
        U[i][j] = A[i][j]
        for k in range(j):
            U[i][j] -= L[i][k]*U[k][j]
        
    for j in range( n):
        U[i][j] = A[i][j]
        L[j][i] = A[j][i]
        for k in range(i):
            U[i][j] -= L[i][k]*U[k][j]
            L[j][i] -= L[j][k]*U[k][i]
        #U[i][j] = U[i][j] 
        L[j][i] = L[j][i]/U[i][i] 

In [58]:
A

array([[  1.      ,   2.      ,   0.5     ,  -5.      ,   0.      ],
       [ -1.3     ,   1.      , -15.      ,   0.      ,   2.      ],
       [  0.333333,   0.      ,   1.234   ,  -4.      ,   4.      ],
       [  0.6666  ,  -5.      ,   1.      ,  30.      ,  -1.      ],
       [  0.      ,   0.05    ,   8.      , -12.      ,  -0.5     ]])

In [59]:
np.dot(L.reshape(-n,n),U)

array([[  1.      ,   2.      ,   0.5     ,  -5.      ,   0.      ],
       [ -1.3     ,   1.      , -15.      ,   0.      ,   2.      ],
       [  0.333333,   0.      ,   1.234   ,  -4.      ,   4.      ],
       [  0.6666  ,  -5.      ,   1.      ,  30.      ,  -1.      ],
       [  0.      ,   0.05    ,   8.      , -12.      ,  -0.5     ]])

In [60]:
z = np.zeros(n)
x = np.zeros(n)

#z by forward substitution
z[0] = b[0]#/L[0][0]
for j in range(1,n):
    z[j] = b[j]
    for k in range(j):
        #print(j)
        #print(("b[%f]= %f")%(j+1,b[j]))
        #print(("L[%f,%f]= %f")%(j+1,k+1,L[j][k]))
        #print(("z[%f]= %f")%(k+1,z[k]))
        z[j] -= L[j][k]*z[k]
    #z[j] = z[j]/L[j][j]
    
#x by backward substitution    
x[n-1] = z[n-1]/U[n-1][n-1]
for j in range(n-2,-1,-1):
    #print(j)
    x[j] = z[j]
    for k in range(j+1,n):
        #print(("z[%f]= %f")%(j+1,z[j]))
        #print(("U[%f,%f]= %f")%(j+1,k+1,U[j][k]))
        #print(("x[%f]= %f")%(k,x[k]))
        x[j] -= U[j][k]*x[k]        

    x[j] = x[j]/U[j][j]

In [61]:
print("2.a) le matrici L e U \n")
print("L: \n",L)
print("U: \n",U)

2.a) le matrici L e U 

L: 
 [[ 1.          0.          0.          0.         -0.        ]
 [-1.3         1.          0.          0.         -0.        ]
 [ 0.333333   -0.185185    1.          0.         -0.        ]
 [ 0.6666     -1.75922222 15.45725633  1.         -0.        ]
 [ 0.          0.01388889 -5.15656487 -0.39373529  1.        ]]
U: 
 [[  1.           2.           0.5         -5.           0.        ]
 [  0.           3.6        -14.35        -6.5          2.        ]
 [  0.           0.          -1.59007125  -3.5370375    4.37037   ]
 [  0.           0.           0.          76.57095083 -65.03548489]
 [  0.           0.           0.          -0.          -3.59844687]]


In [62]:
print("2.b) Il vettore risultato intermedio z\n")
print(z)

2.b) Il vettore risultato intermedio z

[ -11.1666       13.48342      62.78642341 -950.00795283  -53.97666128]


In [63]:
print("2.c) Il vettore risultato finale x\n")
print(x)

2.c) Il vettore risultato finale x

[-9.99997471  0.00001855  0.9999975   0.33333223 14.99998839]


In [46]:
print("2.d) ecc  \n")
x_2 = [-10,0,1,1/3,15]
x_1 = x.copy()
A_1 = A.copy()
b_1 = b.copy()
x_1[2] = 1 #valore esatto
A_1[0][0] = 0.000001
b_1[0] = -1.16665

2.d) ecc  



In [50]:
#d Per poter associare un errore ai valori finali ottenuti, si può operare nel seguente modo:
# sostituire i valore ottenuti in ogni equazione e confrontarli con i valori del vettore b.
# In questo modo, per quanto riguarda x_1, x_3, x_4, x_5 l'errore è praticamente nullo. 
# Invece, per x_2 possiamo associare un errore pari a approx 1^-15
# (anche se arrotondando il valore ottenuto per sostituzione, l'errore è nullo).

b_s = np.zeros(n)
del_x = np.zeros(n)
residuals = np.zeros(n)

for i in range(n):
    for j in range(n):
        b_s[i] += A[i][j]* x_1[j]
    residuals[i] = abs(b_s[i] - b[i])
    del_x[i] = abs(x_2[i] - x[i])

In [51]:
b_s

array([-11.16659875,  27.99996245,  56.56730309, -10.6660975 ,
        -3.49997998])

In [52]:
del_x

array([0.00002529, 0.00001855, 0.0000025 , 0.00000111, 0.00001161])

array([0.00000125, 0.00003755, 0.00000309, 0.0000025 , 0.00002002])

In [38]:
for i in range(n):
    for j in range(n):
        somma += A[i][j]*(x_1[j])
    b_s[i] = somma
    errors[i] = abs(somma - b[i])

2.503023924474091e-06

In [16]:
#l'errore su x3 è 0.000003

In [17]:
# alla fine ci ritroviamo con n*n relazioni, il che significa che ho n*n incognite, e vogliamo ottenere 
# (n**2)/2 coefficienti delle matrici per ciascuno, il problema è che c'è l'elemento diagonale.
# abbiamo quindi (n**2)/2+(n**2)/2+n = n**2+n incognite, per n**2 relazioni, ciò vuol dire che questi n elementi in più
# sono indeterminati e quindi li possiamo assegnare artibtartiamenti (i vari metodi, dooòittle, etc).


In [18]:
#A meno che un sistema possa essere risolto usando numeri interi, la soluzione calcolata, anche se il metodo di 
# Doolittle dà soluzione analitica, sarà quasi sempre approssimato a causa di un errore di troncamento dovuto al 
# calcolatore. 